# Docs: https://circleci.com/docs/2.0/configuration-reference

version: 2.1

workflows:
  hello:
    jobs:
      - helloworld

jobs:
  helloworld:
    steps:
      - greet:
          command: |
            echo 'Hello World!'
