# Docs: https://circleci.com/docs/2.0/configuration-reference

version: 2.1

workflows:
  hello:
    jobs:
      - helloworld

commands:
  helloworld:
    description: 'Just say hello'
    parameters:
      greetee:
        type: string
        default: 'World'
    steps:
      - run: echo 'Hello << parameters.greetee >>!'
